//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jpsys.SagyoManage.FrameLib {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal message() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jpsys.SagyoManage.FrameLib.message", typeof(message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   F1： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001011 {
            get {
                return ResourceManager.GetString("LF1001011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F2： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001021 {
            get {
                return ResourceManager.GetString("LF1001021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F3： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001031 {
            get {
                return ResourceManager.GetString("LF1001031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F4： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001041 {
            get {
                return ResourceManager.GetString("LF1001041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F5：検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001051 {
            get {
                return ResourceManager.GetString("LF1001051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F6：取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001061 {
            get {
                return ResourceManager.GetString("LF1001061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F7：保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001071 {
            get {
                return ResourceManager.GetString("LF1001071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F7：印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001072 {
            get {
                return ResourceManager.GetString("LF1001072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F8：削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001081 {
            get {
                return ResourceManager.GetString("LF1001081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F8：プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001082 {
            get {
                return ResourceManager.GetString("LF1001082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F8：ﾌﾟﾚﾋﾞｭｰ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001083 {
            get {
                return ResourceManager.GetString("LF1001083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F9：終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001091 {
            get {
                return ResourceManager.GetString("LF1001091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F10： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001101 {
            get {
                return ResourceManager.GetString("LF1001101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F11： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001111 {
            get {
                return ResourceManager.GetString("LF1001111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F12：項目後退 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1001121 {
            get {
                return ResourceManager.GetString("LF1001121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F1]前移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002011 {
            get {
                return ResourceManager.GetString("LF1002011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F2]後移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002021 {
            get {
                return ResourceManager.GetString("LF1002021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F3] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002031 {
            get {
                return ResourceManager.GetString("LF1002031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F4] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002041 {
            get {
                return ResourceManager.GetString("LF1002041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F5]検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002051 {
            get {
                return ResourceManager.GetString("LF1002051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F6] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002061 {
            get {
                return ResourceManager.GetString("LF1002061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F7]保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002071 {
            get {
                return ResourceManager.GetString("LF1002071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F7]印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002072 {
            get {
                return ResourceManager.GetString("LF1002072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F8]削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002081 {
            get {
                return ResourceManager.GetString("LF1002081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F8]プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002082 {
            get {
                return ResourceManager.GetString("LF1002082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F8]ﾌﾟﾚﾋﾞｭｰ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002083 {
            get {
                return ResourceManager.GetString("LF1002083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F9]終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002091 {
            get {
                return ResourceManager.GetString("LF1002091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F10] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002101 {
            get {
                return ResourceManager.GetString("LF1002101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F11] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002111 {
            get {
                return ResourceManager.GetString("LF1002111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [F12]項目後退 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LF1002121 {
            get {
                return ResourceManager.GetString("LF1002121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101011 {
            get {
                return ResourceManager.GetString("LT1101011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101021 {
            get {
                return ResourceManager.GetString("LT1101021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101051 {
            get {
                return ResourceManager.GetString("LT1101051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101071 {
            get {
                return ResourceManager.GetString("LT1101071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101072 {
            get {
                return ResourceManager.GetString("LT1101072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101081 {
            get {
                return ResourceManager.GetString("LT1101081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101082 {
            get {
                return ResourceManager.GetString("LT1101082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ﾌﾟﾚﾋﾞｭｰ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101083 {
            get {
                return ResourceManager.GetString("LT1101083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101091 {
            get {
                return ResourceManager.GetString("LT1101091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目後退 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT1101121 {
            get {
                return ResourceManager.GetString("LT1101121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MC2401001 {
            get {
                return ResourceManager.GetString("MC2401001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MC2401002 {
            get {
                return ResourceManager.GetString("MC2401002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム管理者に連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MC2401003 {
            get {
                return ResourceManager.GetString("MC2401003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインできません。入力したID・パスワードを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2301001 {
            get {
                return ResourceManager.GetString("ME2301001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに【{0}】は起動されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2301002 {
            get {
                return ResourceManager.GetString("ME2301002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2302001 {
            get {
                return ResourceManager.GetString("ME2302001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の取得に失敗しました。処理を取り消します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2302002 {
            get {
                return ResourceManager.GetString("ME2302002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2302003 {
            get {
                return ResourceManager.GetString("ME2302003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の削除に失敗しました。処理を取り消します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2302004 {
            get {
                return ResourceManager.GetString("ME2302004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の登録に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2302005 {
            get {
                return ResourceManager.GetString("ME2302005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の登録に失敗しました。処理を取り消します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2302006 {
            get {
                return ResourceManager.GetString("ME2302006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の設定に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2302007 {
            get {
                return ResourceManager.GetString("ME2302007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の作成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2302008 {
            get {
                return ResourceManager.GetString("ME2302008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果の件数が{0}件を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303001 {
            get {
                return ResourceManager.GetString("ME2303001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果の件数が{0}件を超えています。条件を絞って検索しなおしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303002 {
            get {
                return ResourceManager.GetString("ME2303002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の件数が{1}件を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303003 {
            get {
                return ResourceManager.GetString("ME2303003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このデータは他のデータで使用されている為、削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303004 {
            get {
                return ResourceManager.GetString("ME2303004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の{1}に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303005 {
            get {
                return ResourceManager.GetString("ME2303005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」の文字数が長すぎます。
        ///取込対象ファイルの{1}行目を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303006 {
            get {
                return ResourceManager.GetString("ME2303006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が{1}に存在しません。
        ///取込対象ファイルの{2}行目を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303007 {
            get {
                return ResourceManager.GetString("ME2303007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が重複しています。
        ///取込対象ファイルの{1}行目を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303008 {
            get {
                return ResourceManager.GetString("ME2303008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の{1}にアクセスできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303009 {
            get {
                return ResourceManager.GetString("ME2303009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}まで月次締処理済みです。
        ///上記日付までのデータを追加、編集することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303010 {
            get {
                return ResourceManager.GetString("ME2303010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求済みのデータが存在します。
        ///このデータを編集することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303011 {
            get {
                return ResourceManager.GetString("ME2303011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支払済みのデータが存在します。
        ///このデータを編集することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303012 {
            get {
                return ResourceManager.GetString("ME2303012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}まで月次締処理済みです。
        ///上記日付までのデータを追加、編集することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303013 {
            get {
                return ResourceManager.GetString("ME2303013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}まで請求済みです。
        ///上記日付までのデータを追加、編集することはできません。({1}行目) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303014 {
            get {
                return ResourceManager.GetString("ME2303014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}まで支払済みです。
        ///上記日付までのデータを追加、編集することはできません。({1}行目) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303015 {
            get {
                return ResourceManager.GetString("ME2303015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}まで月次締処理済みです。
        ///上記日付までのデータを追加、編集することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303016 {
            get {
                return ResourceManager.GetString("ME2303016", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303017 {
            get {
                return ResourceManager.GetString("ME2303017", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303018 {
            get {
                return ResourceManager.GetString("ME2303018", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303019 {
            get {
                return ResourceManager.GetString("ME2303019", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303020 {
            get {
                return ResourceManager.GetString("ME2303020", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303021 {
            get {
                return ResourceManager.GetString("ME2303021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   まだ「月次締処理」を行っていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303022 {
            get {
                return ResourceManager.GetString("ME2303022", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303023 {
            get {
                return ResourceManager.GetString("ME2303023", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303024 {
            get {
                return ResourceManager.GetString("ME2303024", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303025 {
            get {
                return ResourceManager.GetString("ME2303025", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303026 {
            get {
                return ResourceManager.GetString("ME2303026", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303027 {
            get {
                return ResourceManager.GetString("ME2303027", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303028 {
            get {
                return ResourceManager.GetString("ME2303028", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303029 {
            get {
                return ResourceManager.GetString("ME2303029", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303030 {
            get {
                return ResourceManager.GetString("ME2303030", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303031 {
            get {
                return ResourceManager.GetString("ME2303031", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303032 {
            get {
                return ResourceManager.GetString("ME2303032", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303033 {
            get {
                return ResourceManager.GetString("ME2303033", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303034 {
            get {
                return ResourceManager.GetString("ME2303034", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303035 {
            get {
                return ResourceManager.GetString("ME2303035", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303036 {
            get {
                return ResourceManager.GetString("ME2303036", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303037 {
            get {
                return ResourceManager.GetString("ME2303037", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303038 {
            get {
                return ResourceManager.GetString("ME2303038", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303039 {
            get {
                return ResourceManager.GetString("ME2303039", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303040 {
            get {
                return ResourceManager.GetString("ME2303040", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303041 {
            get {
                return ResourceManager.GetString("ME2303041", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303042 {
            get {
                return ResourceManager.GetString("ME2303042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他の画面から更新されているため、更新できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303043 {
            get {
                return ResourceManager.GetString("ME2303043", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303044 {
            get {
                return ResourceManager.GetString("ME2303044", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303045 {
            get {
                return ResourceManager.GetString("ME2303045", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303046 {
            get {
                return ResourceManager.GetString("ME2303046", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303047 {
            get {
                return ResourceManager.GetString("ME2303047", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303048 {
            get {
                return ResourceManager.GetString("ME2303048", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303049 {
            get {
                return ResourceManager.GetString("ME2303049", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303050 {
            get {
                return ResourceManager.GetString("ME2303050", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303051 {
            get {
                return ResourceManager.GetString("ME2303051", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303052 {
            get {
                return ResourceManager.GetString("ME2303052", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303053 {
            get {
                return ResourceManager.GetString("ME2303053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの形式が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303054 {
            get {
                return ResourceManager.GetString("ME2303054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」の形式が不正です。
        ///取込対象ファイルの{1}行目を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303055 {
            get {
                return ResourceManager.GetString("ME2303055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」の桁数が不正です。
        ///取込対象ファイルの{1}行目を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303056 {
            get {
                return ResourceManager.GetString("ME2303056", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303057 {
            get {
                return ResourceManager.GetString("ME2303057", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303058 {
            get {
                return ResourceManager.GetString("ME2303058", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303059 {
            get {
                return ResourceManager.GetString("ME2303059", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303060 {
            get {
                return ResourceManager.GetString("ME2303060", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303061 {
            get {
                return ResourceManager.GetString("ME2303061", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME2303062 {
            get {
                return ResourceManager.GetString("ME2303062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001001 {
            get {
                return ResourceManager.GetString("MI2001001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に登録されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001002 {
            get {
                return ResourceManager.GetString("MI2001002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に更新されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001003 {
            get {
                return ResourceManager.GetString("MI2001003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に削除されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001004 {
            get {
                return ResourceManager.GetString("MI2001004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更内容は次回ログイン時に反映します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001005 {
            get {
                return ResourceManager.GetString("MI2001005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コードが変更されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001006 {
            get {
                return ResourceManager.GetString("MI2001006", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001007 {
            get {
                return ResourceManager.GetString("MI2001007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に移動されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001008 {
            get {
                return ResourceManager.GetString("MI2001008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に設定されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001009 {
            get {
                return ResourceManager.GetString("MI2001009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷設定を削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001010 {
            get {
                return ResourceManager.GetString("MI2001010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に実行されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001011 {
            get {
                return ResourceManager.GetString("MI2001011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に保存されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001012 {
            get {
                return ResourceManager.GetString("MI2001012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に保存されました。
        ///保存データ継承し、新規伝票を作成できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001013 {
            get {
                return ResourceManager.GetString("MI2001013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}件作成されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001014 {
            get {
                return ResourceManager.GetString("MI2001014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に取り込まれました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001015 {
            get {
                return ResourceManager.GetString("MI2001015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001016 {
            get {
                return ResourceManager.GetString("MI2001016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に作成されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001017 {
            get {
                return ResourceManager.GetString("MI2001017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が完了しました。ファイルを開きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001018 {
            get {
                return ResourceManager.GetString("MI2001018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.{0}で保存されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001019 {
            get {
                return ResourceManager.GetString("MI2001019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}件更新対象中{1}件更新されませんでした。
        ///最新データを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MI2001020 {
            get {
                return ResourceManager.GetString("MI2001020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101001 {
            get {
                return ResourceManager.GetString("MQ2101001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101002 {
            get {
                return ResourceManager.GetString("MQ2101002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101003 {
            get {
                return ResourceManager.GetString("MQ2101003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101004 {
            get {
                return ResourceManager.GetString("MQ2101004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取消してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101005 {
            get {
                return ResourceManager.GetString("MQ2101005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101006 {
            get {
                return ResourceManager.GetString("MQ2101006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101007 {
            get {
                return ResourceManager.GetString("MQ2101007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101008 {
            get {
                return ResourceManager.GetString("MQ2101008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷設定を削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101009 {
            get {
                return ResourceManager.GetString("MQ2101009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101010 {
            get {
                return ResourceManager.GetString("MQ2101010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2101011 {
            get {
                return ResourceManager.GetString("MQ2101011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のデータは保存されません。
        ///終了してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102001 {
            get {
                return ResourceManager.GetString("MQ2102001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当データの変更を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102002 {
            get {
                return ResourceManager.GetString("MQ2102002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示中のデータを削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102003 {
            get {
                return ResourceManager.GetString("MQ2102003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたデータを削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102004 {
            get {
                return ResourceManager.GetString("MQ2102004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された行を削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102005 {
            get {
                return ResourceManager.GetString("MQ2102005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムを終了してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102006 {
            get {
                return ResourceManager.GetString("MQ2102006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集内容を保存してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102007 {
            get {
                return ResourceManager.GetString("MQ2102007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集内容を取消してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102008 {
            get {
                return ResourceManager.GetString("MQ2102008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を変更してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102009 {
            get {
                return ResourceManager.GetString("MQ2102009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択中の行を削除してもよろしいですか？
        ///※確定するには保存をしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102010 {
            get {
                return ResourceManager.GetString("MQ2102010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択中の行の削除を取り消しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102011 {
            get {
                return ResourceManager.GetString("MQ2102011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示された伝票の納入書を印刷します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102012 {
            get {
                return ResourceManager.GetString("MQ2102012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目を行削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102013 {
            get {
                return ResourceManager.GetString("MQ2102013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目に行挿入します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102014 {
            get {
                return ResourceManager.GetString("MQ2102014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロット解除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102015 {
            get {
                return ResourceManager.GetString("MQ2102015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在ロット設定されているデータをすべて{0}します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102016 {
            get {
                return ResourceManager.GetString("MQ2102016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在ロット設定されている下記項目をすべて更新します。よろしいですか？
        ///
        ///【更新項目】
        ///積込日・積込区分・納入日・車両・乗務員
        ///自傭区分・傭車先{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102017 {
            get {
                return ResourceManager.GetString("MQ2102017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在ロット設定されているデータをすべて削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102018 {
            get {
                return ResourceManager.GetString("MQ2102018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を起動します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102019 {
            get {
                return ResourceManager.GetString("MQ2102019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイルを出力します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102020 {
            get {
                return ResourceManager.GetString("MQ2102020", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102021 {
            get {
                return ResourceManager.GetString("MQ2102021", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102022 {
            get {
                return ResourceManager.GetString("MQ2102022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   続けて印刷を行いますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102023 {
            get {
                return ResourceManager.GetString("MQ2102023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力されている内容は上書きされます。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102024 {
            get {
                return ResourceManager.GetString("MQ2102024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示されている明細をすべて保存します。
        ///よろしいですか？
        ///※編集していない明細も保存されますのでご注意ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102025 {
            get {
                return ResourceManager.GetString("MQ2102025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の行のデータが選択された行へ複写されます。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102026 {
            get {
                return ResourceManager.GetString("MQ2102026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先に既に存在します。
        ///上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102027 {
            get {
                return ResourceManager.GetString("MQ2102027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   得意先［{0}］は部門管理する得意先ですが部門が入力されていません。
        ///そのまま処理を続行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102028 {
            get {
                return ResourceManager.GetString("MQ2102028", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102029 {
            get {
                return ResourceManager.GetString("MQ2102029", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102030 {
            get {
                return ResourceManager.GetString("MQ2102030", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102031 {
            get {
                return ResourceManager.GetString("MQ2102031", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102032 {
            get {
                return ResourceManager.GetString("MQ2102032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示されているすべての明細を削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102033 {
            get {
                return ResourceManager.GetString("MQ2102033", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102034 {
            get {
                return ResourceManager.GetString("MQ2102034", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102035 {
            get {
                return ResourceManager.GetString("MQ2102035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された{0}は無効に設定されています。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102036 {
            get {
                return ResourceManager.GetString("MQ2102036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示中の全明細を削除します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102037 {
            get {
                return ResourceManager.GetString("MQ2102037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全明細を削除します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MQ2102038 {
            get {
                return ResourceManager.GetString("MQ2102038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデータは存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201001 {
            get {
                return ResourceManager.GetString("MW2201001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデータは既に存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201002 {
            get {
                return ResourceManager.GetString("MW2201002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力したデータは存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201003 {
            get {
                return ResourceManager.GetString("MW2201003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力したデータは既に存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201004 {
            get {
                return ResourceManager.GetString("MW2201004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデータは削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201005 {
            get {
                return ResourceManager.GetString("MW2201005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力したデータは削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201006 {
            get {
                return ResourceManager.GetString("MW2201006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}した{1}は存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201007 {
            get {
                return ResourceManager.GetString("MW2201007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}した{1}は既に存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201008 {
            get {
                return ResourceManager.GetString("MW2201008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}した{1}は削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201009 {
            get {
                return ResourceManager.GetString("MW2201009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201010 {
            get {
                return ResourceManager.GetString("MW2201010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は既に存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201011 {
            get {
                return ResourceManager.GetString("MW2201011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201012 {
            get {
                return ResourceManager.GetString("MW2201012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先頭データです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201013 {
            get {
                return ResourceManager.GetString("MW2201013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終データです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201014 {
            get {
                return ResourceManager.GetString("MW2201014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当するデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201015 {
            get {
                return ResourceManager.GetString("MW2201015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力したデータは使用停止中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201016 {
            get {
                return ResourceManager.GetString("MW2201016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された{0}データは使用停止中です。{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201017 {
            get {
                return ResourceManager.GetString("MW2201017", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201018 {
            get {
                return ResourceManager.GetString("MW2201018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のデータは削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201019 {
            get {
                return ResourceManager.GetString("MW2201019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力する画像がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201020 {
            get {
                return ResourceManager.GetString("MW2201020", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201021 {
            get {
                return ResourceManager.GetString("MW2201021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理対象の{0}が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2201022 {
            get {
                return ResourceManager.GetString("MW2201022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202001 {
            get {
                return ResourceManager.GetString("MW2202001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202002 {
            get {
                return ResourceManager.GetString("MW2202002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以下です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202003 {
            get {
                return ResourceManager.GetString("MW2202003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以上です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202004 {
            get {
                return ResourceManager.GetString("MW2202004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理対象外の年月です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202005 {
            get {
                return ResourceManager.GetString("MW2202005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理対象外の日付です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202006 {
            get {
                return ResourceManager.GetString("MW2202006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理対象外の時刻です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202007 {
            get {
                return ResourceManager.GetString("MW2202007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より古い年月は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202008 {
            get {
                return ResourceManager.GetString("MW2202008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より新しい年月は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202009 {
            get {
                return ResourceManager.GetString("MW2202009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より古い日付は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202010 {
            get {
                return ResourceManager.GetString("MW2202010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より新しい日付は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202011 {
            get {
                return ResourceManager.GetString("MW2202011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より古い時刻は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202012 {
            get {
                return ResourceManager.GetString("MW2202012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より新しい時刻は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202013 {
            get {
                return ResourceManager.GetString("MW2202013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より{1}は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202014 {
            get {
                return ResourceManager.GetString("MW2202014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より{1}は{2}できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202015 {
            get {
                return ResourceManager.GetString("MW2202015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202016 {
            get {
                return ResourceManager.GetString("MW2202016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}より{2}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202017 {
            get {
                return ResourceManager.GetString("MW2202017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の範囲指定に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202018 {
            get {
                return ResourceManager.GetString("MW2202018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は「{1}～{2}」の範囲で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202019 {
            get {
                return ResourceManager.GetString("MW2202019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAXの設定が完了していません。
        ///メニューバーから「FAXの設定」をクリックし、FAXの設定を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202020 {
            get {
                return ResourceManager.GetString("MW2202020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以降を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202021 {
            get {
                return ResourceManager.GetString("MW2202021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本日以前の日付は指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202022 {
            get {
                return ResourceManager.GetString("MW2202022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}より前の日付は入力できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202023 {
            get {
                return ResourceManager.GetString("MW2202023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}から{1}まで7日間以上は設定はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202024 {
            get {
                return ResourceManager.GetString("MW2202024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}～{1}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202025 {
            get {
                return ResourceManager.GetString("MW2202025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象期間は{0}ヶ月以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202026 {
            get {
                return ResourceManager.GetString("MW2202026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2202032 {
            get {
                return ResourceManager.GetString("MW2202032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203001 {
            get {
                return ResourceManager.GetString("MW2203001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203002 {
            get {
                return ResourceManager.GetString("MW2203002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}明細が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203003 {
            get {
                return ResourceManager.GetString("MW2203003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203004 {
            get {
                return ResourceManager.GetString("MW2203004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203005 {
            get {
                return ResourceManager.GetString("MW2203005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが確認用と一致していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203006 {
            get {
                return ResourceManager.GetString("MW2203006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムパスワードが一致していません。入力内容を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203007 {
            get {
                return ResourceManager.GetString("MW2203007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   修正対象を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203008 {
            get {
                return ResourceManager.GetString("MW2203008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細が選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203009 {
            get {
                return ResourceManager.GetString("MW2203009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が重複しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203010 {
            get {
                return ResourceManager.GetString("MW2203010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}には{1}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203011 {
            get {
                return ResourceManager.GetString("MW2203011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203012 {
            get {
                return ResourceManager.GetString("MW2203012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203013 {
            get {
                return ResourceManager.GetString("MW2203013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203014 {
            get {
                return ResourceManager.GetString("MW2203014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に不正な値が入力されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203015 {
            get {
                return ResourceManager.GetString("MW2203015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   まいと～くFAX ActiveX コントロールの利用開始に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203016 {
            get {
                return ResourceManager.GetString("MW2203016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAX送信処理に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203017 {
            get {
                return ResourceManager.GetString("MW2203017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAX送信ソフトがインストールされていません。
        ///システム管理者にお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203018 {
            get {
                return ResourceManager.GetString("MW2203018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}で桁あふれが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203019 {
            get {
                return ResourceManager.GetString("MW2203019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定されているプリンタが見つかりません。
        ///プリンタが削除された可能性があります。
        ///再度、設定を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203020 {
            get {
                return ResourceManager.GetString("MW2203020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビューでは確定データ作成は行えません。
        ///確定データは「印刷」ボタン押下時のみ作成されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203021 {
            get {
                return ResourceManager.GetString("MW2203021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始日～終了日は過去日以外指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203022 {
            get {
                return ResourceManager.GetString("MW2203022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された{0}の保存パスは見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203023 {
            get {
                return ResourceManager.GetString("MW2203023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は、エクセルファイルしか指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203024 {
            get {
                return ResourceManager.GetString("MW2203024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は、パワーポイントファイルしか指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203025 {
            get {
                return ResourceManager.GetString("MW2203025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧から削除する{0}を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203026 {
            get {
                return ResourceManager.GetString("MW2203026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}しか指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203027 {
            get {
                return ResourceManager.GetString("MW2203027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイルが {0}件 出力されました。ファイルを開きますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203028 {
            get {
                return ResourceManager.GetString("MW2203028", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203029 {
            get {
                return ResourceManager.GetString("MW2203029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始＞終了です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203030 {
            get {
                return ResourceManager.GetString("MW2203030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力対象とする項目を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203031 {
            get {
                return ResourceManager.GetString("MW2203031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力解除する項目を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203032 {
            get {
                return ResourceManager.GetString("MW2203032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力対象の項目がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203033 {
            get {
                return ResourceManager.GetString("MW2203033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個別指定の最大数{0}を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203034 {
            get {
                return ResourceManager.GetString("MW2203034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}になるまで処理を実行することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203035 {
            get {
                return ResourceManager.GetString("MW2203035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存する画像ファイルがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203036 {
            get {
                return ResourceManager.GetString("MW2203036", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203037 {
            get {
                return ResourceManager.GetString("MW2203037", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203038 {
            get {
                return ResourceManager.GetString("MW2203038", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203039 {
            get {
                return ResourceManager.GetString("MW2203039", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203040 {
            get {
                return ResourceManager.GetString("MW2203040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先が見つかりません。
        ///{0}
        ///出力先を確認するか、変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203041 {
            get {
                return ResourceManager.GetString("MW2203041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}まで請求締め確定処理済みです。
        ///上記日付までのデータを編集、削除することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203042 {
            get {
                return ResourceManager.GetString("MW2203042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この伝票は、{0}分までの請求締め処理の対象分です。
        ///この伝票を編集、削除した場合は、請求締め処理をもう一度やり直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203043 {
            get {
                return ResourceManager.GetString("MW2203043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この伝票は、{0}分までの請求締め処理の対象分です。
        ///処理を続行した場合、請求締め処理をやり直す必要があります。
        ///このまま処理を続行する場合は「はい」、中止する場合は「いいえ」を押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203044 {
            get {
                return ResourceManager.GetString("MW2203044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した得意先は、既に{0}分までの請求締め処理を開始しています。
        ///処理を続行した場合、請求締め処理をやり直す必要があります。
        ///このまま処理を続行する場合は「はい」、中止する場合は「いいえ」を押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203045 {
            get {
                return ResourceManager.GetString("MW2203045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票の修正・削除は、入力日+1日までです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203046 {
            get {
                return ResourceManager.GetString("MW2203046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在、他の利用者にて請求処理が行われているため、処理できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203047 {
            get {
                return ResourceManager.GetString("MW2203047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求締切処理が行われていません。やり直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203048 {
            get {
                return ResourceManager.GetString("MW2203048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求締切確定処理が行われていないため、処理できません。
        ///締切クリア処理、または確定締切処理後に行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203049 {
            get {
                return ResourceManager.GetString("MW2203049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}データを削除する権限はありません。
        ///参照、または登録のみ可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203050 {
            get {
                return ResourceManager.GetString("MW2203050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}データを登録・削除する権限はありません。
        ///参照のみ可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203051 {
            get {
                return ResourceManager.GetString("MW2203051", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203052 {
            get {
                return ResourceManager.GetString("MW2203052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「農場指定」「餌コード確定」「納入コメント」が設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203053 {
            get {
                return ResourceManager.GetString("MW2203053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じロットに設定されている配車情報と{0}が異なります！
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203054 {
            get {
                return ResourceManager.GetString("MW2203054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同一 積込日・積込区分・納入日・車両・乗務員 のデータが存在します。ロット設定を行いますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203055 {
            get {
                return ResourceManager.GetString("MW2203055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   積載容量を超えています！{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203056 {
            get {
                return ResourceManager.GetString("MW2203056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   積込日・納入日の確認をしてください！
        ///4日以上空いています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203057 {
            get {
                return ResourceManager.GetString("MW2203057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入量＜＞{0}対象トン数です！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203058 {
            get {
                return ResourceManager.GetString("MW2203058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   積込日＜＞{0}対象日です！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203059 {
            get {
                return ResourceManager.GetString("MW2203059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業時間が重なっています！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203060 {
            get {
                return ResourceManager.GetString("MW2203060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   向こう{0}日間で、餌が変わります。
        ///置き換えますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203061 {
            get {
                return ResourceManager.GetString("MW2203061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この餌はパターンに含まれていません！
        ///{0}：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203062 {
            get {
                return ResourceManager.GetString("MW2203062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パターンの餌納入量を超えています！
        ///{0}：{1}
        ///今後：{2}　予定：{3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203063 {
            get {
                return ResourceManager.GetString("MW2203063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}この農場タンクへは移動できません！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203064 {
            get {
                return ResourceManager.GetString("MW2203064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   換羽期間が重複しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203065 {
            get {
                return ResourceManager.GetString("MW2203065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：{1}は有薬飼料です！
        ///{2}に出荷が予定されています！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203066 {
            get {
                return ResourceManager.GetString("MW2203066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額が大きすぎます！{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203067 {
            get {
                return ResourceManager.GetString("MW2203067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パターンの合計餌納入量を超えています！
        ///今後：{0}　予定：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203068 {
            get {
                return ResourceManager.GetString("MW2203068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大表示行数の{0}件を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203069 {
            get {
                return ResourceManager.GetString("MW2203069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された{0}は存在しません。{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203070 {
            get {
                return ResourceManager.GetString("MW2203070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した{0}は使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203071 {
            get {
                return ResourceManager.GetString("MW2203071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に使用できない文字が含まれています。
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203072 {
            get {
                return ResourceManager.GetString("MW2203072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が作成されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203073 {
            get {
                return ResourceManager.GetString("MW2203073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このタンクは保証なしに設定されています！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203074 {
            get {
                return ResourceManager.GetString("MW2203074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未使用データに設定されていますが、使用しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203075 {
            get {
                return ResourceManager.GetString("MW2203075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求部門に設定されている得意先と異なる得意先は指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203076 {
            get {
                return ResourceManager.GetString("MW2203076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支払日は締日以降の日付を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203077 {
            get {
                return ResourceManager.GetString("MW2203077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手形期日は支払日以降の日付を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203078 {
            get {
                return ResourceManager.GetString("MW2203078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   傭車先しか指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW2203079 {
            get {
                return ResourceManager.GetString("MW2203079", resourceCulture);
            }
        }
    }
}
